# used to salt the users' password hashes
password_secret = "[REDACTED]"
# used to generate filenames for static content
content_secret = "[REDACTED]"

[public_info]
name = "ヒカマーBooru"
default_user_rank = "regular"
enable_safety = true

username_regex = "^[a-zA-Z0-9_-]{1,32}$"
password_regex = "^.{5,}$"
tag_name_regex = "^\\S+$"
tag_category_name_regex = "^[^\\s%+#/]+$"

[public_info.privileges]
# --- users ---
user_create_self = "anonymous"
user_list = "anonymous"
user_view = "anonymous"
user_edit_self_name = "anonymous"
user_edit_self_pass = "anonymous"
user_edit_self_email = "anonymous"
user_edit_self_avatar = "anonymous"
user_delete_self = "anonymous"

# --- posts ---
post_create_anonymous = "anonymous"
post_create_identified = "anonymous"
post_list = "anonymous"
post_view = "anonymous"
post_view_featured = "anonymous"
post_edit_tag = "anonymous"
post_edit_safety = "anonymous"
post_edit_source = "anonymous"
post_edit_relation = "anonymous"
post_edit_note = "anonymous"
post_edit_description = "anonymous"
post_edit_flag = "anonymous"
post_score = "anonymous"
post_favorite = "anonymous"
post_delete = "regular"

# --- comments ---
comment_create = "anonymous"
comment_list = "anonymous"
comment_view = "anonymous"
comment_score = "anonymous"
comment_edit_own = "anonymous"
comment_delete_own = "anonymous"

# --- tags ---
tag_create = "anonymous"
tag_list = "anonymous"
tag_view = "anonymous"
tag_edit_name = "anonymous"
tag_edit_description = "anonymous"
tag_delete = "regular"

# --- pools ---
pool_create = "anonymous"
pool_list = "anonymous"
pool_view = "anonymous"
pool_edit_post = "anonymous"
pool_delete = "regular"

# --- uploads ---
upload_create = "anonymous"
